services:
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: claims_user
      POSTGRES_PASSWORD: claims_password
      POSTGRES_DB: claims_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U claims_user -d claims_db -h localhost -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend_py
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend_py/.env
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:4000/api
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:3000"

volumes:
  db_data: