services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: cc
      POSTGRES_PASSWORD: cc
      POSTGRES_DB: cc
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cc -d cc"]
      interval: 2s
      timeout: 5s
      retries: 30

  backend:
    build:
      context: ./backend_py
      dockerfile: Dockerfile
    env_file:
      - ./backend_py/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:4000
    depends_on:
      - backend
    ports:
      - "8080:3000"

volumes:
  pgdata:
